name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
permissions:
  contents: read
on: [push]
jobs:
  demo-nodejs-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install --cache /tmp/empty-cache
      - run: npm run build
      - run: npm test
