name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  demo-nodejs-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci --no-audit --fund=false
      - run: npm run build
      - run: npm test
